### ISSUE TITLE
Separate public API from internal code

### ISSUE THREAD

**Issue by johnsonr** [atomist/github-sdm#102]
Certain types, like the event types and listener signatures, should be considered stable and identified as such. Other types, like the event handlers, are not directly user visible.

This will significantly reduce the change of changes breaking user code, and enable the potential of separating these types into their own repo in time.

**Comment by ddgenome** [comment]
I would recommend doing this by creating an src/index.ts file that imports and exports what we want public. That way, people can just

```typescript
import { blah } from "@atomist/github-sdm";
```
