### ISSUE TITLE
Phase tracing rather than phase lists

### ISSUE THREAD

**Issue by claymccoy** [atomist/github-sdm#114]
Right now you have a hardcoded list of phases to declare what is planned to happen. But that isn't the only way to get the phase plan. You could have something like a tracer bullet that sends the events through the system in a dry run (no side effects), but only puts together the list of phases that will run.

It would make the runtime simpler because we could have the event handlers be specific about the context of the status event they expect without cringing that we are declaring the phase order in multiple places that have to be consistent (the list of phases would not be necessary). We currently get a lot of event handlers triggered because they are listening for very general subscriptions (like any successful status).

It gives us more capabilities than just a linear set of phases. They could be much more dynamic with looping, conditional, and parallel phases.

It gives us traceability through the system. It could be useful for more than just the dry run that records the plan. We could use it to test at the level of event handler orchestration. This is something we don't currently have a good answer for.

Thoughts?

**Comment by johnsonr** [comment]
Makes sense. Would be good to consider how the present `PhraseCreator` would differ in that case. Phases are presently computed dynamically on a push. There's no support yet for parallel phases, although I think we could defer that.

**Comment by claymccoy** [comment]
After thinking about it a bit more, we are basically building a crude workflow engine on top of the Atomist platform. I have some reservations about that.
Of course, what we are doing with phases can be improved (by using custom events rather than GitHub statuses, maybe making the planned execution dynamic rather than a list as mentioned above, among other things...). But the current use of phases seems a bit egregious in places. It makes sense to have an event round trip to kick off another event handler that is in a different automation. Maybe it is even reasonable in the same automation when you plan to break one event handler out on its own or want to ensure extreme decoupling like we do in parts of the sdm. But using so many phases, granular event handlers with general subscriptions and guard cases, and string manipulation doesn't seem like the ideal default way to structure an automation. It is difficult to reason about and modify.
I'm not suggesting all the usages of phases in the sdm are bad, but I think they should all serve a purpose. There are places where we intercept status events from other systems just to update a different internal phase status for use within the sdm. If we had a dedicated phase event and consistent usage when integrating with another system and decoupling internal components things start to make more sense. Even then, a lot of the local logic flow could be done with promises or a real workflow lib.

**Comment by claymccoy** [comment]
One blind spot we have is the orchestration of multiple event handlers. It would be nice to write a unit test with several event handlers that work together. You could initialize the event handlers, mock side effects, add them all to a registry, kick one off, and then make assertions about the event trace through them.
This would be pretty easy to do if we had a local in-memory version of the routing capabilities in the Atomist server API. I'd like to be able to start this up in my event handler unit tests, add data (instead of sending to a webhook) and run graphql queries on it. I looked around a bit to see if anything like this exists and came up with nothing. There are graphql mocking libraries and local caches for use with clients. But they stop short of actually running a query on the data. I looked more closely at how we do this in the client only to find out that all the important event routing is handled on the server.

**Comment by johnsonr** [comment]
@jessitron work on goals etc should have addressed this
