### ISSUE TITLE
Remove duplicate classes once multiple subscriptions are allowed

### ISSUE THREAD

**Issue by johnsonr** [atomist/github-sdm#139]
Classes like `DeployFromLocalOnSuccessStatus1` only exist because of a problem in subscription conflict that may have been resolved by @cdupuis . Remove them and test.

**Comment by johnsonr** [comment]
This requires upgrading `automation-client`, which means upgrading `spring-automation` also

**Comment by jessitron** [comment]
this was eliminated by #179
