### ISSUE TITLE
Issue topic tagging incorrectly removes topics set by other taggers

### ISSUE THREAD

**Issue by johnsonr** [atomist/github-sdm#211]
Additional taggers, such as node tagger, can overwrite tags. E.g. enabling the node tagger causes it to overwrite Spring tags, resulting none.

*Should only add and never delete tags.*

`publishTags` should be cleverer.

**Comment by cdupuis** [comment]
@johnsonr is this about issues labels or repo topics?

**Comment by jessitron** [comment]
now I see this:
```Tagging `satellite-of-love/serov` with tags `spring-boot`, `spring`, `java`

Tagging `satellite-of-love/serov` with tags```

it should like not say anything when it doesn't add any

i'm betting you can fix this in about 2 minutes because you know where it is
