### ISSUE TITLE
SDM should clearly show emitted event handlers in startup log

### ISSUE THREAD

**Issue by johnsonr** [atomist/github-sdm#261]
Which handlers are emitted is important and reflects decisions based on listener registration. It should be clearly displayed in the startup log.

**Comment by johnsonr** [comment]
Ideally, should output after registration JSON from client, which isn't of much practical use.

Also, should go to console, rather than log.

**Comment by cdupuis** [comment]
Yes, yes and yes. I’ll do that.

**Comment by cdupuis** [comment]
I can print the handlers as part of the banner.

**Comment by johnsonr** [comment]
Fixed
