### ISSUE TITLE
Remove "deploy to production" message after deployment

### ISSUE THREAD

**Issue by johnsonr** [atomist/github-sdm#36]

**Comment by jessitron** [comment]
I was thinking we'd change it to "Completed deploy of [sha-link] to production, requested by slackuser"

**Comment by johnsonr** [comment]
@jessitron Is this still unresolved?

**Comment by jessitron** [comment]
yes, and I propose removing the production diff until we can improve it

**Comment by johnsonr** [comment]
Can we create a new issue for chockalog that restores the diff
@jessitron ?

**Comment by jessitron** [comment]
this issue is no longer relevant; moved to #213
